version: '2'
services:
  # To interact with the chain enter the `miner` docker service with `geth` as such;
  #    docker exec -it miner geth attach --exec 'eth.accounts'
  #
  # Scripts in the `./scripts` directory can be launched as such;
  #    docker exec -it miner geth attach --preload '/scripts/test/barriers-bytecode.js' --exec 'loadScript("/scripts/test/barriers-deploy.js")'
  #    docker exec -it miner geth attach --preload '/scripts/test/barriers-bytecode.js' --exec 'loadScript("/scripts/test/navigate-contracts.js")'
  miner:
    container_name: "miner"
    image: ethereum/client-go:alltools-v1.9.16
    command: "geth --datadir ./volume/datadir --dev --dev.period 2 --ipcpath=/root/.ethereum/geth.ipc"
    volumes:
      - ./scripts:/scripts
