version: '2'
services:
  miner:
    container_name: "miner"
    image: ethereum/client-go:alltools-v1.9.16
    command: "geth --datadir ./volume/datadir --dev --dev.period 2 --ipcpath=/root/.ethereum/geth.ipc"
    volumes:
      - ./scripts:/scripts
