version: '2'
services:
  miner:
    container_name: "miner"
    image: ethereum/client-go:alltools-v1.9.16
    command: "geth --datadir ./volume/datadir --dev --dev.period 1 --rpcapi personal,db,eth,net,web3 --rpc --rpcaddr 0.0.0.0"
    ports:
      - "8545:8545"
